os:
  - linux

sudo: false

language: go

env:
  matrix:
    - BUILD_DEPTYPE=gomod


go:
  - 1.12.x

install: false

script:
  - bash <(curl -s https://raw.githubusercontent.com/ipfs/ci-helpers/master/travis-ci/run-standard-tests.sh)

cache:
  directories:
    - $GOPATH/src/gx
    - $GOPATH/pkg/mod
    - $HOME/.cache/go-build

notifications:
  email: false
